spring.application.name=grpc-mock
# gRPC Server Configuration
grpc.server.port=9090
# grpc.server.shutdown-grace-period=30s # Optional: Graceful shutdown period

# Logging
logging.level.com.example.grpcpoc=DEBUG
logging.level.net.devh.boot.grpc.server=INFO
